apiVersion: v1
metadata:
  name: aws-auth
  namespace: kube-system
kind: ConfigMap
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<CLIENT_ACCOUNT_ID>:role/iam_management_eks_role
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<CLIENT_ACCOUNT_ID>:role/iam_management_eks_role
      username: management
